-- Database seeding SQL script
INSERT INTO `product`
(`price`,
`description`,
`path`)
VALUES 
(2.00,
'A sunny morning in Noblesville',
'resources/backyard.jpeg'),
(1.00,
'This elegent building is home to the largest performance hall on campus.',
'resources/bsu-emens.jpeg'),
(1.00,
'If you have an eye for details, you may find these chalk drawings hiding around campus',
'resources/bsu-frog.jpeg'),
(1.00,
'Beware of the BSU honkers',
'resources/bsu-honkers.jpeg'),
(1.00,
'Where the music students perform',
'resources/bsu-morning-sursa.jpeg'),
(1.00,
'The main road on campus',
'resources/bsu-night-mckinley.jpeg'),
(1.00,
'BSU at night',
'resources/bsu-night-skies.jpeg'),
(1.00,
'The scramble light on a rainy day',
'resources/bsu-scramblelight.jpeg'),
(1.00,
'A whiteboard in the Jazz room',
'resources/bsu-whiteboard.jpeg'),
(1.00,
'Snowy trees near the Burkhart Building',
'resources/bsu-winter-trees.jpeg'),
(1.00,
'The view from the Soldiers and Sailors Monument in Indy',
'resources/indy-skies.jpeg'),
(1.00,
'The Indy skyline view from the Monon Trail',
'resources/monon.jpeg'),
(0.50,
'A busy street in NYC',
'resources/ny-streets.jpeg');

INSERT INTO `tag`
(`name`)
VALUES
('morning'),
('night'),
('scenary'),
('geese'),
('people'),
('buildings');

INSERT INTO `product_has_tag`
(`product_id`,
`tag_id`)
VALUES
(1, 1),
(1, 3),
(2, 4),
(2, 6),
(3, 6),
(4, 3),
(4, 4),
(5, 1),
(5, 3),
(5, 6),
(6, 2),
(6, 3),
(6, 6),
(7, 2),
(7, 3),
(7, 6),
(8, 1),
(9, 5),
(9, 6),
(10, 3),
(11, 3),
(11, 6),
(11, 3),
(12, 3),
(12, 6),
(13, 5);